#!/bin/bash

if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0
fi

CURRENT_DIR=$(basename $(pwd))

NETWORK_NAME=mqtt-network

if [ ! "$(docker network ls | grep "$NETWORK_NAME")" ]; then
  echo "Creating network ..."
  docker network create $NETWORK_NAME
fi

docker run -it --name postgres  \
    -e POSTGRES_USER=root \
    -e POSTGRES_PASSWORD=root \
    -e POSTGRES_DB=MontreConnectee \
    -p 5432:5432 \
    -v $(pwd)/init.sql:/dockert-entrypoint-initdb.d/init.sql \
    --net $NETWORK_NAME \
    -d postgres

docker run -it --name pgadmin \
    -e PGADMIN_DEFAULT_EMAIL=admin@gmail.com \
    -e PGADMIN_DEFAULT_PASSWORD=root \
    -p 8080:80 \
    --net $NETWORK_NAME \
    -d dpage/pgadmin4
